### ISSUE TITLE
Form to join a camp

### ISSUE THREAD

**Issue by RoySegall** [Midburn/burning#41]

**Comment by ripper234** [comment]
Can we have a screenshot preview here of how that form looks like?
When is this planned for production deployment?

**Comment by RoySegall** [comment]
Will be deployed at some point. You can install this project on your local machine and test it,

**Comment by ripper234** [comment]
Sadly I don't have time to play with Drupal and install it.

If a screenshot could be pasted here, that would be great.
If you don't have time for that, that's great too :)
